telegram:
  token: token
  bot_name: name

weather:
  appid: 85aa52a555dac6ac36c4ecffbe15e13d
  url:
    city: http://api.openweathermap.org/data/2.5/weather?q={city}&APPID=${weather.appid}&units=metric&lang=ru
    location: https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid=${weather.appid}&units=metric&lang=ru